--- #YAML:1.0
name:               Device-Dynamixel
version:            0.023
abstract:           Simple control of Robotis Dynamixel servo motors
author:
    - Dima Kogan <dkogan@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Const::Fast:  0
    perl:         5.1
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
